require 'rubygems'
require 'enhanced_marc'
require 'frbr'
require File.dirname(__FILE__) + '/frbr_marc/work'
require File.dirname(__FILE__) + '/frbr_marc/expression'
require File.dirname(__FILE__) + '/frbr_marc/manifestion'
require File.dirname(__FILE__) + '/frbr_marc/item' 
require File.dirname(__FILE__) + '/frbr_marc/analyzer'
require File.dirname(__FILE__) + '/frbr_marc/aggregation'
